### ISSUE TITLE
`pytest-asyncio` version conflict

### ISSUE THREAD

**Issue by AustinScola** [pheanex/pytest-aioresponses#1]
Hi @pheanex, I tried to use `pyest-aioresponses` and had a minor problem with a dependency conflict.

My project specifies `pytest-ascyncio==0.15.1` but it looks like `pytest-aioresponses 0.1.0` depends on `pytest-asyncio<0.15.0` and `>=0.14.0`:
https://github.com/pheanex/pytest-aioresponses/blob/32d409c19f79758da8e519bb2c41609187213e22/pyproject.toml#L33

Can we loosen this restriction?

**Comment by pheanex** [comment]
Hey @AustinScola, sure. What do you suggest / Want to send a PR?

**Comment by pheanex** [comment]
I've just released version 0.2.0 on [PyPI](https://pypi.org/project/pytest-aioresponses/).
Can you check if this fixes your problem?

**Comment by YaraslauZhylko** [comment]
Sorry for reviving the thread.

Why do we even require `pytest-asyncio` for `pytest-aioresponses`?
It does not seem to be used in the library itself.
And for the async testing in general, one can install either `pytest-asyncio` or any of the alternatives like `pytest-anyio`.

Should `pytest-asyncio` be removed from the dependencies altogether? :thinking:

**Comment by pheanex** [comment]
@YaraslauZhylko I'm wondering the same now.  As we do not seem to use it, do you want to raise a pr to remove it?

**Comment by YaraslauZhylko** [comment]
@pheanex Sure.
Here you are: #4

**Comment by pheanex** [comment]
Closing this as we merged the MR (with removing the dependency). Will release soon. Thanks again both of you :blush:

**Comment by pheanex** [comment]
I've uploaded the 0.3.0 release with this change. Check it out [here](https://pypi.org/project/pytest-aioresponses/).

**Comment by YaraslauZhylko** [comment]
@pheanex Seems to be working as expected.
No extra dependencies installed.
